project:
  type: book

book:
  title: "고전 역학"
  author: "Norah Jones"
  date: "7/1/2023"
  chapters:
    - index.qmd
    - part: docs/Lanczos/Lanczos.qmd
      chapters :
      - docs/Lanczos/00_01.qmd
      - docs/Lanczos/01_01.qmd
      - docs/Lanczos/02_01.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



