project:
  type: book

book:
  title: "고전 역학과 전자기학"
  author: "Norah Jones"
  date: "2/11/2024"
  page-navigation: true

  
  chapters:
    - index.qmd
    - part: docs/ClassicalMechanics/00_index.qmd
      chapters:
      - docs/ClassicalMechanics/01_basic_principles.qmd
      - docs/ClassicalMechanics/02_variational_principle.qmd
      - docs/ClassicalMechanics/03_hamilton_dynamics.qmd
      - docs/ClassicalMechanics/one_body_problems.qmd
      - docs/ClassicalMechanics/two_or_three_bodies_problems.qmd
      - docs/ClassicalMechanics/A_proofs.qmd
      
    - part: docs/Electromagnetism/00_index.qmd
      chapters:
      - docs/Electromagnetism/01_Maxwell.qmd
    - part: docs/Relativity/00_index.qmd
      chapters:
      - docs/Relativity/01_introduction_to_special_relativity.qmd
      - docs/Relativity/02_introduction_to_classical_field.qmd
    - part: docs/Lanczos/Lanczos.qmd
      chapters:
      - docs/Lanczos/00_01.qmd
      - docs/Lanczos/01_01.qmd
      - docs/Lanczos/02_01.qmd
    - part: docs/topics/Topics.qmd
      chapters:
        - docs/topics/mathematical.qmd
    - part: docs/images/images.qmd
      chapters:
      - docs/images/images_classical_mechanics_01.qmd
      - docs/images/images_classical_mechanics_02.qmd
      - docs/images/images_relativity_01.qmd
      - docs/images/images_test.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    title-block-banner: true
    # include-in-header: 
    #   - html-hacks/load-font-awesome.html
    #   - html-hacks/load-xkcd-font.html
    # resources: web-resources/**
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    # theme: darkly
    theme: cosmo
    fontsize: 0.9em
    toc: true
    collapse: true
    # css: styles.css
    number-sections: true
  



