project:
  type: book

book:
  title: "고전 역학"
  author: "Norah Jones"
  date: "2/11/2024"
  page-navigation: true

  
  chapters:
    - index.qmd
    - part: docs/BasicClassicalMechanics/00_index.qmd
      chapters:
      - docs/BasicClassicalMechanics/01_basic_principles.qmd
      - docs/BasicClassicalMechanics/02_variational_principle.qmd
      - docs/BasicClassicalMechanics/03_hamilton_dynamics.qmd
    - part: docs/Relativity/00_index.qmd
      chapters:
      - docs/Relativity/01_introduction_to_special_relativity.qmd
      - docs/Relativity/02_introduction_to_classical_field.qmd
    - part: docs/Lanczos/Lanczos.qmd
      chapters:
      - docs/Lanczos/00_01.qmd
      - docs/Lanczos/01_01.qmd
      - docs/Lanczos/02_01.qmd
    - part: docs/images/images.qmd
      chapters:
      - docs/images/images_01.qmd
      - docs/images/images_02.qmd
      - docs/images/images_test.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
    fontsize: 0.9em
    toc: true



