project:
  type: book

book:
  title: "고전 역학"
  author: "Norah Jones"
  date: "2/11/2024"
  page-navigation: true

  
  chapters:
    - index.qmd
    - part: docs/Lanczos/Lanczos.qmd
      chapters:
      - docs/Lanczos/00_01.qmd
      - docs/Lanczos/01_01.qmd
      - docs/Lanczos/02_01.qmd
    - part: docs/Goldstein/Goldstein.qmd
      chapters:
      - docs/Goldstein/01.qmd
      - docs/Goldstein/02.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fontsize: 0.9em
    toc: true



